/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Order;

import DTOService.Constanst;
import DTOService.GeneralMethod;
import View.MainJFrame;
import com.itextpdf.text.DocumentException;
import controller.FileController.UserController;
import controller.NhapController.KhachHangController;
import controller.NhapController.SanPhamController;
import controller.Orders.OrderController;
import model.BanHang.OrderDetail;
import model.BanHang.SPDetail;
import model.DTO.DetailCustomer;
import model.DTO.OrderDetailDisplay;
import model.File.Theme;
import model.Nhap.KhachHang;
import model.Nhap.SanPham;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author choco
 */
public class OrderPanel extends javax.swing.JPanel {

    GeneralMethod GM = new GeneralMethod();
    private MainJFrame mainJFrame;
    KhachHangController KC = new KhachHangController();
    SanPhamController SP = new SanPhamController();
    OrderController OC = new OrderController();
    UserController UC = new UserController();
    DefaultTableModel nameKhModel;
    DefaultTableModel nameSpModel;
    DefaultTableModel orderModel;
    //int loaiKhach = 0;
    int typeSale = MainJFrame.sellingMethod;

    List<OrderDetail> listOrderDetail = new ArrayList<>();
    public static String codeOrderDraft = "";

    /**
     * Creates new form OrderCreate
     */
    public OrderPanel(MainJFrame mainJFrame) {
        initComponents();
//setting
        String discount = MainJFrame.dis + "";
        listOrderDetail.removeAll(listOrderDetail);
        ///khai set mau ---------------

        this.mainJFrame = mainJFrame;
        nameKhModel = (DefaultTableModel) nameKhTable.getModel();
        nameSpModel = (DefaultTableModel) nameSPTable.getModel();
        orderModel = (DefaultTableModel) orderTable.getModel();
        orderModel.setRowCount(0);
        // xử    lý hiển thị combobox
        GM.formatClassCombobx(boxLoaiSP, SP.getLoaiSP());
        GM.formatClassCombobx(boxNV, UC.getAllName());

        // ẩn cột code(id)
        orderTable.getColumnModel().getColumn(0).setMinWidth(0);
        orderTable.getColumnModel().getColumn(0).setMaxWidth(0);

        // set max Size của từng cột
        orderTable.getColumnModel().getColumn(1).setMaxWidth(70);
        orderTable.getColumnModel().getColumn(2).setMaxWidth(50);

        dialogListKh.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                OrderPanel.this.mainJFrame.setEnabled(true);
                OrderPanel.this.mainJFrame.setVisible(true);
            }
        });
        nameSPDialog.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                OrderPanel.this.mainJFrame.setEnabled(true);
                OrderPanel.this.mainJFrame.setVisible(true);
            }
        });
      //  cleanAllForm();

        if (codeOrderDraft.length() > 0) {
            listOrderDetail = OC.getListOrderDetail(codeOrderDraft);
            showOrderTable(listOrderDetail);
            showCustomerDetail(OC.getDetailCustomer(codeOrderDraft));
            codeOrderDraft = "";
        }
        //set icon
        GM.setButtonIcon(btnAddSP, "../View/images/icon/add.png", 50);
        GM.setButtonIcon(btnSaveDraft, "../View/images/icon/daft.png", 50);
        GM.setButtonIcon(btnResetTable, "../View/images/icon/dept.png", 50);
        GM.setButtonIcon(btnSell, "../View/images/icon/sell.png", 50);
        int x = this.mainJFrame.getLocationOnScreen().x + 400;
        int y = this.mainJFrame.getLocationOnScreen().y + 100;
        nameSPDialog.setLocation(x, y);
        dialogListKh.setLocation(x, y);
        setColor();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogListKh = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        nameKhTable = new javax.swing.JTable();
        okNameKHDialog = new javax.swing.JButton();
        nameKhInsert = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        nameSPDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        nameSPTable = new javax.swing.JTable();
        nameSPInsert = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        okNameSP = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        btnSaveDraft = new javax.swing.JButton();
        btnAddSP = new javax.swing.JButton();
        btnSell = new javax.swing.JButton();
        boxLoaiSP = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        btnTenKh = new javax.swing.JPanel();
        btnNhapKHText = new javax.swing.JLabel();
        btnNhapTenHang = new javax.swing.JPanel();
        btnTenHangText = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        sdtText = new javax.swing.JLabel();
        ghiChuText = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        soLuongText = new javax.swing.JTextField();
        tongTienPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tamTinhView = new javax.swing.JLabel();
        tongTienView = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        giamGiaText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        boxNV = new javax.swing.JComboBox<>();
        btnResetTable = new javax.swing.JButton();
        cocText = new javax.swing.JTextField();

        dialogListKh.setUndecorated(true);
        dialogListKh.setSize(new java.awt.Dimension(500, 400));

        nameKhTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Tên Đại Lý"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                    false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        nameKhTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameKhTableMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nameKhTableMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(nameKhTable);

        okNameKHDialog.setText("OK");
        okNameKHDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okNameKHDialogMouseClicked(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                okNameKHDialogMousePressed(evt);
            }
        });
        okNameKHDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okNameKHDialogActionPerformed(evt);
            }
        });

        nameKhInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameKhInsertActionPerformed(evt);
            }
        });
        nameKhInsert.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKhInsertKeyTyped(evt);
            }
        });

        jLabel12.setText("Tên Đại Lý: ");

        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(nameKhInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(53, Short.MAX_VALUE))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(okNameKHDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nameKhInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12))
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(okNameKHDialog)
                                        .addComponent(jButton2))
                                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogListKhLayout = new javax.swing.GroupLayout(dialogListKh.getContentPane());
        dialogListKh.getContentPane().setLayout(dialogListKhLayout);
        dialogListKhLayout.setHorizontalGroup(
                dialogListKhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogListKhLayout.setVerticalGroup(
                dialogListKhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        nameSPDialog.setUndecorated(true);
        nameSPDialog.setSize(new java.awt.Dimension(500, 371));

        nameSPTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Mã hàng", "Tên Mặt Hàng"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                    false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        nameSPTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameSPTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(nameSPTable);

        nameSPInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSPInsertActionPerformed(evt);
            }
        });
        nameSPInsert.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameSPInsertKeyTyped(evt);
            }
        });

        jLabel6.setText("Mã hàng:");

        okNameSP.setText("OK");
        okNameSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                okNameSPMousePressed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameSPInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(75, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(okNameSP, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(nameSPInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(okNameSP)
                                        .addComponent(jButton1))
                                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout nameSPDialogLayout = new javax.swing.GroupLayout(nameSPDialog.getContentPane());
        nameSPDialog.getContentPane().setLayout(nameSPDialogLayout);
        nameSPDialogLayout.setHorizontalGroup(
                nameSPDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(nameSPDialogLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0))
        );
        nameSPDialogLayout.setVerticalGroup(
                nameSPDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(nameSPDialogLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(890, 371));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Dịch vụ / Sản phẩm");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("Tên khách:");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("SĐT:");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setText("Mã hàng:");

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel20.setText("Ghi chú:");

        jLabel21.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel21.setText("SL:");

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "", "Check", "STT", "Mã Hàng", "Tên DV / SP", "Số Lượng", "Đơn Giá", "Thành Tiền"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                    true, true, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        orderTable.setDragEnabled(true);
        jScrollPane1.setViewportView(orderTable);
        if (orderTable.getColumnModel().getColumnCount() > 0) {
            orderTable.getColumnModel().getColumn(2).setMinWidth(20);
            orderTable.getColumnModel().getColumn(2).setMaxWidth(50);
        }

        btnSaveDraft.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSaveDraft.setText("Lưu nháp");
        btnSaveDraft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSaveDraft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSaveDraftMousePressed(evt);
            }
        });

        btnAddSP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAddSP.setText("Thêm");
        btnAddSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAddSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddSPMouseClicked(evt);
            }
        });

        btnSell.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSell.setText("Nhận đơn");
        btnSell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSellMousePressed(evt);
            }
        });

        boxLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        boxLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxLoaiSPActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel22.setText("Cọc:");

        btnTenKh.setBackground(new java.awt.Color(255, 255, 255));
        btnTenKh.setPreferredSize(new java.awt.Dimension(200, 25));
        btnTenKh.setVerifyInputWhenFocusTarget(false);
        btnTenKh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTenKhMouseClicked(evt);
            }
        });

        btnNhapKHText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNhapKHText.setText("Click để nhập");
        btnNhapKHText.setPreferredSize(new java.awt.Dimension(76, 25));
        btnNhapKHText.setRequestFocusEnabled(false);
        btnNhapKHText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhapKHTextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnTenKhLayout = new javax.swing.GroupLayout(btnTenKh);
        btnTenKh.setLayout(btnTenKhLayout);
        btnTenKhLayout.setHorizontalGroup(
                btnTenKhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btnTenKhLayout.createSequentialGroup()
                                .addComponent(btnNhapKHText, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0))
        );
        btnTenKhLayout.setVerticalGroup(
                btnTenKhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnNhapKHText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnNhapTenHang.setBackground(new java.awt.Color(255, 255, 255));
        btnNhapTenHang.setVerifyInputWhenFocusTarget(false);

        btnTenHangText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTenHangText.setText("Click để nhập");
        btnTenHangText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTenHangTextMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnNhapTenHangLayout = new javax.swing.GroupLayout(btnNhapTenHang);
        btnNhapTenHang.setLayout(btnNhapTenHangLayout);
        btnNhapTenHangLayout.setHorizontalGroup(
                btnNhapTenHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btnNhapTenHangLayout.createSequentialGroup()
                                .addComponent(btnTenHangText, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0))
        );
        btnNhapTenHangLayout.setVerticalGroup(
                btnNhapTenHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnNhapTenHangLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnTenHangText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(140, 25));

        sdtText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sdtText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sdtText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ghiChuText.setPreferredSize(new java.awt.Dimension(14, 26));
        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(140, 25));

        soLuongText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        soLuongText.setPreferredSize(new java.awt.Dimension(152, 25));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(soLuongText, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addGap(0, 0, 0))
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(soLuongText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        tongTienPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Tạm tính:");

        jLabel8.setText("Giảm giá:");

        jLabel10.setText("Tổng tiền:");

        tamTinhView.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tamTinhView.setPreferredSize(new java.awt.Dimension(234, 18));

        tongTienView.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tongTienView.setPreferredSize(new java.awt.Dimension(234, 18));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel15.setText("-");

        giamGiaText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Đơn hàng của: ");

        boxNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

        javax.swing.GroupLayout tongTienPanelLayout = new javax.swing.GroupLayout(tongTienPanel);
        tongTienPanel.setLayout(tongTienPanelLayout);
        tongTienPanelLayout.setHorizontalGroup(
                tongTienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tongTienPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxNV, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(tongTienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tongTienPanelLayout.createSequentialGroup()
                                                .addGroup(tongTienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(47, 47, 47)
                                                .addGroup(tongTienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tongTienPanelLayout.createSequentialGroup()
                                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(tongTienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(tongTienPanelLayout.createSequentialGroup()
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(tamTinhView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(tongTienPanelLayout.createSequentialGroup()
                                                                                .addGap(5, 5, 5)
                                                                                .addComponent(giamGiaText, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addComponent(tongTienView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );
        tongTienPanelLayout.setVerticalGroup(
                tongTienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tongTienPanelLayout.createSequentialGroup()
                                .addGroup(tongTienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(tongTienPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(tongTienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel7)
                                                        .addComponent(tamTinhView, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(tongTienPanelLayout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addGroup(tongTienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(boxNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tongTienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(giamGiaText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                        .addGroup(tongTienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel15)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(tongTienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(tongTienPanelLayout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(tongTienView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(tongTienPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(3, 3, 3))
        );

        btnResetTable.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnResetTable.setText("Update");
        btnResetTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnResetTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetTableMouseClicked(evt);
            }
        });

        cocText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1)
                                                        .addComponent(tongTienPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(btnSaveDraft, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnAddSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnSell, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                                        .addComponent(btnResetTable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(boxLoaiSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel9)
                                                                .addGap(17, 17, 17))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btnNhapTenHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnTenKh, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel21))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel20)
                                                        .addComponent(jLabel22))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cocText)
                                                        .addComponent(ghiChuText, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(5, 5, 5)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel22)
                                                                        .addComponent(cocText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel3)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel21)
                                                                        .addComponent(jLabel20)
                                                                        .addComponent(ghiChuText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(btnNhapTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnTenKh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(boxLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(btnAddSP, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnResetTable, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnSaveDraft, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tongTienPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setColor() {
        // main view
        Theme theme = MainJFrame.listTheme.get(0);
        boxLoaiSP.setBackground(Color.decode(theme.getBackgroundTextField()));
        boxNV.setBackground(Color.decode(theme.getBackgroundTextField()));

        orderTable.getTableHeader().setOpaque(false);
        orderTable.getTableHeader().setBackground(Color.decode(theme.getBackgroundTittleTable()));
        btnAddSP.setBackground(Color.decode(theme.getBackgroundButton()));
        btnSell.setBackground(Color.decode(theme.getBackgroundButton()));
        btnResetTable.setBackground(Color.decode(theme.getBackgroundButton()));
        btnSaveDraft.setBackground(Color.decode(theme.getBackgroundButton()));
        this.setBackground(Color.decode(theme.getBackgroundMainPanel()));
        jLabel1.setForeground(Color.decode(theme.getTxtColorTitle()));
        jLabel3.setForeground(Color.decode(theme.getTxtColorTitle()));
        jLabel4.setForeground(Color.decode(theme.getTxtColorTitle()));
        jLabel22.setForeground(Color.decode(theme.getTxtColorTitle()));
        jLabel9.setForeground(Color.decode(theme.getTxtColorTitle()));
        jLabel20.setForeground(Color.decode(theme.getTxtColorTitle()));
        jLabel21.setForeground(Color.decode(theme.getTxtColorTitle()));
        //nameSPDialog
        jLabel12.setForeground(Color.decode(theme.getTxtColorTitle()));
        // jLabel2.setForeground(Color.decode(theme.getTxtColorTitle()));

        jPanel1.setBackground(Color.decode(theme.getBackgroundMainPanel()));
        nameKhTable.getTableHeader().setOpaque(false);
        nameKhTable.getTableHeader().setBackground(Color.decode(theme.getBackgroundTittleTable()));
        okNameKHDialog.setBackground(Color.decode(theme.getBackgroundButton()));
        jButton1.setBackground(Color.decode(theme.getBackgroundButton()));
        //dialogListKh
        jButton2.setBackground(Color.decode(theme.getBackgroundButton()));
        jLabel6.setForeground(Color.decode(theme.getTxtColorTitle()));
        jPanel2.setBackground(Color.decode(theme.getBackgroundMainPanel()));
        nameSPTable.getTableHeader().setOpaque(false);
        nameSPTable.getTableHeader().setBackground(Color.decode(theme.getBackgroundTittleTable()));
        okNameSP.setBackground(Color.decode(theme.getBackgroundButton()));
    }

    private void boxLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxLoaiSPActionPerformed
        // TODO add your handling code here:
//        try {
//            String loaiSP = boxLoaiSP.getSelectedItem().toString();
//            if (loaiSP.equalsIgnoreCase("Dịch vụ")) {
//                btnSell.setText("Nhận đơn");
//            } else {
//                btnSell.setText("Bán");
//
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_boxLoaiSPActionPerformed

    private void btnNhapKHTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapKHTextMouseClicked
//        if (boxLoaiKhach.getSelectedIndex() == 1) {
//            dialogListKh.setVisible(true);
//            this.mainJFrame.setEnabled(false);
//            loaiKhach = 1;
//        } else if (boxLoaiKhach.getSelectedIndex() == 2) {
//            dialogListKh.setVisible(true);
//            this.mainJFrame.setEnabled(false);
//            loaiKhach = 2;
//        }
        dialogListKh.setVisible(true);
        this.mainJFrame.setEnabled(false);
        nameKhInsert.setEditable(true);
        try {
            String loaiSP = boxLoaiSP.getSelectedItem().toString();
            if (loaiSP.equalsIgnoreCase("Dịch vụ")) {
                btnSell.setText("Nhận đơn");
            } else {
                btnSell.setText("Bán");

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnNhapKHTextMouseClicked

    private void nameKhTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameKhTableMouseClicked
        int row = nameKhTable.getSelectedRow();
        String name = nameKhInsert.getText();

        String nameSP = nameKhModel.getValueAt(row, 0).toString();

        nameKhInsert.setText(nameSP);
        nameKhInsert.setEditable(false);
    }//GEN-LAST:event_nameKhTableMouseClicked

    private void okNameKHDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okNameKHDialogMouseClicked

    }//GEN-LAST:event_okNameKHDialogMouseClicked

    private void okNameKHDialogMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okNameKHDialogMousePressed
        String name = nameKhInsert.getText();
        if (name.trim().length() > 0) {
            btnNhapKHText.setText(name);
            dialogListKh.setVisible(false);
            this.mainJFrame.setEnabled(true);
            this.mainJFrame.setVisible(true);
            setInfor(name);
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng kiểm tra lại tên sản phẩm");

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_okNameKHDialogMousePressed

    private void okNameKHDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okNameKHDialogActionPerformed

    }//GEN-LAST:event_okNameKHDialogActionPerformed

    private void nameKhInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameKhInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameKhInsertActionPerformed

    private void nameKhInsertKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKhInsertKeyTyped
        String nameKH = nameKhInsert.getText();
        List<String> listNameKH = new ArrayList<>();
        if (nameKH.length() >= 1) {
            listNameKH = KC.getNameKh(nameKH);
            showKHTable(listNameKH);
        }
    }//GEN-LAST:event_nameKhInsertKeyTyped

    private void btnTenKhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTenKhMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnTenKhMouseClicked

    private void nameKhTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameKhTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_nameKhTableMouseEntered

    private void btnTenHangTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTenHangTextMousePressed
        nameSPInsert.setText("");
        nameSpModel.setRowCount(0);
        nameSPDialog.setVisible(true);
        nameSPInsert.setEditable(true);

        this.mainJFrame.setEnabled(false);

    }//GEN-LAST:event_btnTenHangTextMousePressed

    private void nameSPInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSPInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameSPInsertActionPerformed

    private void nameSPInsertKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameSPInsertKeyTyped
        String nameSP = nameSPInsert.getText();
        List<SanPham> listNameSP;
        String loaiSP = boxLoaiSP.getSelectedItem().toString();
        String thuongHieu = "Select";
        if (nameSP.length() >= 1) {
            listNameSP = SP.getNameSanPham(thuongHieu, loaiSP, nameSP);
            showNameSpTable(listNameSP);

        }

    }//GEN-LAST:event_nameSPInsertKeyTyped

    private void nameSPTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameSPTableMouseClicked
        int row = nameSPTable.getSelectedRow();
        String name = nameSPInsert.getText();
        String nameSP = nameSpModel.getValueAt(row, 0).toString();
        nameSPInsert.setText(nameSP);
        nameSPInsert.setEditable(false);
    }//GEN-LAST:event_nameSPTableMouseClicked

    //lấy tên sản phẩm
    private void okNameSPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okNameSPMousePressed
        String codeProduct = nameSPInsert.getText();
        if (codeProduct.trim().length() > 0) {
            btnTenHangText.setText(codeProduct);
            nameSPDialog.setVisible(false);

            this.mainJFrame.setEnabled(true);
            this.mainJFrame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng kiểm tra lại tên sản phẩm");

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_okNameSPMousePressed

    // thêm sản phẩm vào bảng
    private void btnAddSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddSPMouseClicked
        // thêm sp vào bảng đồng thời thêm vào list SP
        btnAddSP.setVisible(false);
        try {
            int soLuong = 0;
            int ck = 0;
            try {
                soLuong = Integer.parseInt(soLuongText.getText());
                ck = 1;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Số lượng phải là kiểu số nguyên");

            }
            String codeProduct = btnTenHangText.getText();
            int giamGia = Integer.parseInt(cocText.getText());

            List<SanPham> listSP = SP.getSPCode(codeProduct);
            String codeSP = listSP.get(0).getCodeSP();
            String nameSP = listSP.get(0).getName();
            if (soLuong > 0) {
                if (soLuong <= OC.getTotalSP(codeSP) && ck == 1) {
                    List<SPDetail> listSPDetail = new ArrayList<>();
                    listSPDetail = OC.getListSPDetailOut(typeSale, codeSP, soLuong);
                    for (SPDetail lts : listSPDetail) {
                        OrderDetail record = new OrderDetail(lts.getCodeSPDetail(), codeProduct, nameSP, lts.getQuantity(),
                                lts.getPriceOut(), lts.getQuantity() * lts.getPriceOut());
                        listOrderDetail.add(record);
                    }
                    showOrderTable(listOrderDetail);
                    // set Tam tinh
                    int tamTinh = 0;
                    for (OrderDetail lts : listOrderDetail) {
                        tamTinh += lts.getAmount();
                    }
                    tamTinhView.setText(GM.doubleToDecimal(tamTinh));
                    //set giam gia
                    //int giamGia = 0;
                    try {
                        giamGia = Integer.parseInt(giamGiaText.getText());

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Trường giảm giá phải là kiểu số ");
                        return;
                    }
                    //setTong tien
                    int tongTien = tamTinh - giamGia;
                    tongTienView.setText(GM.doubleToDecimal(tongTien));
                    //  JOptionPane.showMessageDialog(null, "Thêm thành công");
                    cleanSPForm();
                } else {
                    JOptionPane.showMessageDialog(null, "Số lượng sản phẩm lớn hơn trong kho");

                }
            } else {
                JOptionPane.showMessageDialog(null, "Số lượng sản phẩm phải lớn hơn 0");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lưu ý các trường dữ liệu");
        }
        nameKhInsert.setEditable(false);
        btnAddSP.setVisible(true);
    }//GEN-LAST:event_btnAddSPMouseClicked

    //lưu nháp
    private void btnSaveDraftMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveDraftMousePressed
        // lưu nháp
        resetTable();
        //  int loaiKhach = boxLoaiKhach.getSelectedIndex();
        String codeUser = MainJFrame.codeUser;
        String nameKhach = btnNhapKHText.getText();
        String codeKH = KC.getKhCode(nameKhach);
        String tt = tongTienView.getText();

        Double tongTien = Double.parseDouble(tt.replace(",", ""));
        Double giamGia = 0.0;
        Double coc = 0.0;
        try {
            giamGia = Double.parseDouble(giamGiaText.getText().replace(",",""));
            coc = Double.parseDouble(cocText.getText().replace(",",""));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Các trường tiền tệ phải là kiểu số ");
        }
        String status = Constanst.ORDER_DRAFT;
        // inset vào bảng order
        int ck = 0;
        String codeOrder = GM.randIdCreate();
        if (OC.insertOrder(codeOrder, codeUser, codeKH, coc, giamGia, tongTien, status)) {
            for (OrderDetail lts : listOrderDetail) {
                String codeOrderDetail = GM.randIdCreate();
                //ínert vào bảng orderDetail
                if (OC.insertOrderDetail(codeOrderDetail, codeOrder, lts.getCodeSPDetail(), lts.getQuantity(), lts.getPrice())) {
                    ck = ck + 1;
                }
            }
        }
        if (ck == listOrderDetail.size()) {
            JOptionPane.showMessageDialog(null, "Lưu nháp thành công");
            cleanAllForm();
        } else {
            JOptionPane.showMessageDialog(null, "Lưu nháp thất bại");
        }

    }//GEN-LAST:event_btnSaveDraftMousePressed

    // bán thanh toán ngay
    private void btnSellMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSellMousePressed
        // bán thanh toán ngay
        resetTable();
        //int loaiKhach = boxLoaiKhach.getSelectedIndex();
        String codeUser = MainJFrame.codeUser;
        String nameKhach = btnNhapKHText.getText();
        String codeKH = KC.getKhCode(nameKhach);
        Double giamGia = 0.0;
        Double coc = 0.0;
        try {
            giamGia = Double.parseDouble(giamGiaText.getText().replace(",",""));
            coc = Double.parseDouble(cocText.getText().replace(",",""));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Các trường tiền tệ phải là kiểu số ");

        }
        String loaiSP = boxLoaiSP.getSelectedItem().toString();
        String userName = boxNV.getSelectedItem().toString();
        String tt = tongTienView.getText();
        Double tongTien = Double.parseDouble(tt.replace(",", ""));
        String status = "PROCESS";
        String description = "Thu tiền cọc từ " + nameKhach;
        // inset vào transaction
        String codeOrder = GM.randIdCreate();
        if (OC.transactionBanHang(codeOrderDraft, codeOrder, codeUser, codeKH, coc, giamGia, tongTien, status,
                listOrderDetail, description, loaiSP,userName)) {
            JOptionPane.showMessageDialog(null, "Thành công");

            try {
                OC.PDF(listOrderDetail, nameKhach, codeOrder);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (DocumentException ex) {
                Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            cleanAllForm();
        } else {
            JOptionPane.showMessageDialog(null, "Thất Bại");
        }

    }//GEN-LAST:event_btnSellMousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        nameSPDialog.setVisible(false);
        this.mainJFrame.setEnabled(true);
        this.mainJFrame.setVisible(true);
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        dialogListKh.setVisible(false);
        this.mainJFrame.setEnabled(true);
        this.mainJFrame.setVisible(true);
    }//GEN-LAST:event_jButton2MousePressed

    private void btnResetTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetTableMouseClicked
        // TODO add your handling code here:
        resetTable();
    }//GEN-LAST:event_btnResetTableMouseClicked
    // method tự viết thêm-------------------------------------------------

    private void resetTable() {
        this.mainJFrame.setEnabled(false);
        try {
            int n = listOrderDetail.size();
            listOrderDetail.removeAll(listOrderDetail);
            for (int i = 0; i < n; i++) {
                OrderDetail rc = new OrderDetail();
                rc.setCodeSPDetail(orderTable.getValueAt(i, 0).toString());
                rc.setCode_Product(orderTable.getValueAt(i, 3).toString());
                rc.setNameSP(orderTable.getValueAt(i, 4).toString());
                rc.setQuantity(Integer.parseInt(orderTable.getValueAt(i, 5).toString()));
                String priceTable = orderTable.getValueAt(i, 6).toString();
                if (priceTable.contains(",")) {
                    priceTable = priceTable.replace(",", "");
                }
                rc.setPrice(Double.parseDouble(priceTable));
                rc.setAmount(rc.getQuantity() * rc.getPrice());
                listOrderDetail.add(rc);
            }
            showOrderTable(listOrderDetail);
            // set Tam tinh
            int tamTinh = 0;
            for (OrderDetail lts : listOrderDetail) {
                tamTinh += lts.getAmount();
            }
            tamTinhView.setText(GM.doubleToDecimal(tamTinh));
            //set giam gia
            int giamGia = 0;
            try {
                giamGia = Integer.parseInt(giamGiaText.getText().replace(",",""));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Trường tiền tệ phải là kiểu số ");
            }
            //setTong tien
            int tongTien = tamTinh - giamGia;
            tongTienView.setText(GM.doubleToDecimal(tongTien));
        } catch (Exception e) {

        }
        this.mainJFrame.setEnabled(true);
    }

    public void cleanAllForm() {
        codeOrderDraft = "";
        nameSPInsert.setEditable(true);
        nameSPInsert.setText("");
        nameKhInsert.setEditable(true);
        nameKhInsert.setText("");
        nameKhModel.setRowCount(0);
        nameSpModel.setRowCount(0);
        //  boxLoaiKhach.setSelectedIndex(0);
        boxLoaiSP.setSelectedIndex(0);
        btnNhapKHText.setText("Click để nhập");
        btnTenHangText.setText("Click để nhập");
        soLuongText.setText("");
        sdtText.setText("");
        ghiChuText.setText("");
        listOrderDetail.removeAll(listOrderDetail);
        orderModel.setRowCount(0);
        giamGiaText.setText("0");
        tamTinhView.setText("");
        tongTienView.setText("");
        cocText.setText("0");

    }

    public void cleanSPForm() {
        nameSPInsert.setText("");
        nameSpModel.setRowCount(0);
        boxLoaiSP.setSelectedIndex(0);
        btnTenHangText.setText("Click để nhập");
        soLuongText.setText("");
    }

    public void showKHTable(List<String> list) {
        nameKhModel.setRowCount(0);
        for (String lts : list) {
            nameKhModel.addRow(new Object[]{
                lts
            });
        }

    }

    public void showNameSpTable(List<SanPham> list) {
        nameSpModel.setRowCount(0);
        for (SanPham lts : list) {
            nameSpModel.addRow(new Object[]{
                lts.getProductCode(), lts.getName()
            });
        }
    }

    public void showOrderTable(List<OrderDetail> list) {
        int no = 1;
        orderModel.setRowCount(0);
        for (OrderDetail lts : list) {
            orderModel.addRow(new Object[]{
                lts.getCodeSPDetail(), new Boolean(false), no++, lts.getCode_Product(), lts.getNameSP(), lts.getQuantity(),
                GM.doubleToDecimal(lts.getPrice()), GM.doubleToDecimal(lts.getAmount())
            });
        }

    }

    public void showDetailOrderTable(List<OrderDetailDisplay> list) {
        int no = 1;
        orderModel.setRowCount(0);
        for (OrderDetailDisplay lts : list) {
            orderModel.addRow(new Object[]{
                lts.getCodeSPDetail(), new Boolean(false), no++, lts.getNameSp(), GM.doubleToDecimal(lts.getDonGiaXuat()), lts.getSl(), GM.doubleToDecimal(lts.getSl() * lts.getDonGiaXuat())
            });
        }
    }

    public void showCustomerDetail(DetailCustomer detailCustomer) {
        try {
            btnNhapKHText.setText(detailCustomer.getNameKH());
            sdtText.setText(detailCustomer.getPhone());
            cocText.setText(GM.doubleToDecimal(detailCustomer.getCoc()));
            giamGiaText.setText(GM.doubleToDecimal(detailCustomer.getGiamGia()));
            tongTienView.setText(GM.doubleToDecimal(detailCustomer.getTongTien()));
            Double tamTinh = detailCustomer.getTongTien() + detailCustomer.getGiamGia();
            tamTinhView.setText(GM.doubleToDecimal(tamTinh));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void setInfor(String nameKH) {
        List<KhachHang> listKh = new ArrayList<KhachHang>();
        listKh = KC.getKhInfor(nameKH);
        if (listKh.size() > 0) {
            sdtText.setText(listKh.get(0).getSdt());
        }

    }

    public void formatBoxLoaiKhach(JComboBox box) {
        box.removeAllItems();
        box.addItem("Khách Lẻ");
        box.addItem("Khách quen ");
        box.addItem("Đại lý");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxLoaiSP;
    private javax.swing.JComboBox<String> boxNV;
    private javax.swing.JButton btnAddSP;
    private javax.swing.JLabel btnNhapKHText;
    private javax.swing.JPanel btnNhapTenHang;
    private javax.swing.JButton btnResetTable;
    private javax.swing.JButton btnSaveDraft;
    private javax.swing.JButton btnSell;
    private javax.swing.JLabel btnTenHangText;
    private javax.swing.JPanel btnTenKh;
    private javax.swing.JTextField cocText;
    private javax.swing.JDialog dialogListKh;
    private javax.swing.JTextField ghiChuText;
    private javax.swing.JTextField giamGiaText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nameKhInsert;
    private javax.swing.JTable nameKhTable;
    private javax.swing.JDialog nameSPDialog;
    private javax.swing.JTextField nameSPInsert;
    private javax.swing.JTable nameSPTable;
    private javax.swing.JButton okNameKHDialog;
    private javax.swing.JButton okNameSP;
    private javax.swing.JTable orderTable;
    private javax.swing.JLabel sdtText;
    private javax.swing.JTextField soLuongText;
    private javax.swing.JLabel tamTinhView;
    private javax.swing.JPanel tongTienPanel;
    private javax.swing.JLabel tongTienView;
    // End of variables declaration//GEN-END:variables
}
