/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.*;
import javax.swing.*;

import DTOService.GeneralMethod;
import View.Order.OrderDeptPanel;
import View.Order.OrderComplete;
import View.Order.OrderDraftPanel;
import View.Order.OrderPanel;
import model.File.Theme;

/**
 *
 * @author choco
 */
public class BHPanel extends javax.swing.JPanel {

    private MainJFrame mainJFrame;
    GeneralMethod GM = new GeneralMethod();
    Theme theme = MainJFrame.listTheme.get(0);

    /**
     * Creates new form BHPanel
     */
    public BHPanel(MainJFrame mainJFrame) {
        initComponents();
        this.mainJFrame = mainJFrame;

        GM.setLabelIcon(iconCreate, MainJFrame.url + "ordercreate.png");
        GM.setLabelIcon(iconDraft, MainJFrame.url + "orderdraft.png");
        GM.setLabelIcon(iconDebt, MainJFrame.url + "orderdept.png");
        GM.setLabelIcon(iconSold, MainJFrame.url + "ordercomplete.png");

        mainPanel.setBackground(Color.decode("#adadad"));
        this.setBackground(Color.decode(theme.getBackgroundTaskPanel()));
        setOriginColor(new JPanel[]{btn_create, btn_draft, btn_debt, btn_sold});
        Theme theme = MainJFrame.listTheme.get(0);
        mainPanel.setBackground(Color.decode(theme.getBackgroundMainPanel()));
    }

    public void setSelectedColor(JPanel jp) {
        jp.setBackground(Color.decode(theme.getBackgroundTaskPanelClick()));

    }

    public void resetColor(JPanel[] pane) {
        for (int i = 0; i < pane.length; i++) {
            pane[i].setBackground(Color.decode(theme.getBackgroundTaskPanel()));

        }
    }

    public void setOriginColor(JPanel[] pane) {
        for (int i = 0; i < pane.length; i++) {
            pane[i].setBackground(Color.decode(theme.getBackgroundTaskPanel()));

        }
    }

    public JPanel returnBHPanel() {
        return this.mainPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_create = new javax.swing.JPanel();
        iconCreate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_draft = new javax.swing.JPanel();
        iconDraft = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_sold = new javax.swing.JPanel();
        iconSold = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_debt = new javax.swing.JPanel();
        iconDebt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(212, 210, 210));
        setPreferredSize(new java.awt.Dimension(890, 459));

        btn_create.setBackground(new java.awt.Color(179, 177, 177));
        btn_create.setPreferredSize(new java.awt.Dimension(100, 88));
        btn_create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_createMousePressed(evt);
            }
        });

        iconCreate.setAlignmentX(0.5F);
        iconCreate.setPreferredSize(new java.awt.Dimension(60, 60));
        iconCreate.setVerifyInputWhenFocusTarget(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhận đơn");

        javax.swing.GroupLayout btn_createLayout = new javax.swing.GroupLayout(btn_create);
        btn_create.setLayout(btn_createLayout);
        btn_createLayout.setHorizontalGroup(
            btn_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_createLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        btn_createLayout.setVerticalGroup(
            btn_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_createLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(iconCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        btn_draft.setBackground(new java.awt.Color(179, 177, 177));
        btn_draft.setPreferredSize(new java.awt.Dimension(100, 88));
        btn_draft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_draftMousePressed(evt);
            }
        });

        iconDraft.setAlignmentX(0.5F);
        iconDraft.setPreferredSize(new java.awt.Dimension(60, 60));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Đơn nháp");

        javax.swing.GroupLayout btn_draftLayout = new javax.swing.GroupLayout(btn_draft);
        btn_draft.setLayout(btn_draftLayout);
        btn_draftLayout.setHorizontalGroup(
            btn_draftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_draftLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(iconDraft, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(btn_draftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_draftLayout.setVerticalGroup(
            btn_draftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_draftLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(iconDraft, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(3, 3, 3))
        );

        btn_sold.setBackground(new java.awt.Color(179, 177, 177));
        btn_sold.setPreferredSize(new java.awt.Dimension(100, 88));
        btn_sold.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_soldMousePressed(evt);
            }
        });

        iconSold.setAlignmentX(0.5F);
        iconSold.setPreferredSize(new java.awt.Dimension(60, 60));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Đơn đã trả");

        javax.swing.GroupLayout btn_soldLayout = new javax.swing.GroupLayout(btn_sold);
        btn_sold.setLayout(btn_soldLayout);
        btn_soldLayout.setHorizontalGroup(
            btn_soldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_soldLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        btn_soldLayout.setVerticalGroup(
            btn_soldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_soldLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(iconSold, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_debt.setBackground(new java.awt.Color(179, 177, 177));
        btn_debt.setPreferredSize(new java.awt.Dimension(100, 88));
        btn_debt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_debtMousePressed(evt);
            }
        });

        iconDebt.setAlignmentX(0.5F);
        iconDebt.setPreferredSize(new java.awt.Dimension(60, 60));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Đơn chưa trả");

        javax.swing.GroupLayout btn_debtLayout = new javax.swing.GroupLayout(btn_debt);
        btn_debt.setLayout(btn_debtLayout);
        btn_debtLayout.setHorizontalGroup(
            btn_debtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_debtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_debtLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(iconDebt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        btn_debtLayout.setVerticalGroup(
            btn_debtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_debtLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(iconDebt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        mainPanel.setPreferredSize(new java.awt.Dimension(890, 371));
        mainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_draft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_debt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btn_sold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_draft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_debt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_createMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_createMousePressed
        setSelectedColor(btn_create);
        resetColor(new JPanel[]{btn_draft, btn_debt, btn_sold});
        GM.showPanel(mainPanel, new OrderPanel(this.mainJFrame));

    }//GEN-LAST:event_btn_createMousePressed

    private void btn_draftMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_draftMousePressed
        setSelectedColor(btn_draft);
        resetColor(new JPanel[]{btn_create, btn_debt, btn_sold});
        GM.showPanel(mainPanel, new OrderDraftPanel(this.mainJFrame, this));
    }//GEN-LAST:event_btn_draftMousePressed

    private void btn_soldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_soldMousePressed
        setSelectedColor(btn_sold);
        resetColor(new JPanel[]{btn_draft, btn_debt, btn_create});
        GM.showPanel(mainPanel, new OrderComplete());
    }//GEN-LAST:event_btn_soldMousePressed

    private void btn_debtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_debtMousePressed
        setSelectedColor(btn_debt);
        resetColor(new JPanel[]{btn_draft, btn_create, btn_sold});
        GM.showPanel(mainPanel, new OrderDeptPanel());

    }//GEN-LAST:event_btn_debtMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_create;
    private javax.swing.JPanel btn_debt;
    private javax.swing.JPanel btn_draft;
    private javax.swing.JPanel btn_sold;
    private javax.swing.JLabel iconCreate;
    private javax.swing.JLabel iconDebt;
    private javax.swing.JLabel iconDraft;
    private javax.swing.JLabel iconSold;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
