/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DTOService.GeneralMethod;
import controller.FileController.OptionController;
import controller.FileController.ThemeController;
import controller.NhapController.SanPhamController;

import java.awt.*;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import model.File.Discount;
import model.File.Option;
import model.File.Theme;

/**
 *
 * @author choco
 */
public class MainJFrame extends javax.swing.JFrame {

    public static String codeUser = "";
    public static String userName = "";
    public static String permisson = "";
    public static String nameTheme = "";
    public static int sellingMethod = 0;
    public static int dis = 0;
    public static LocalDate discountFromDate;
    public static LocalDate discountToDate;
    public static String url = "src/images/rectang/";
    public static String urlIcon = "src/images/icon/";

    GeneralMethod GM = new GeneralMethod();
    public static List<Theme> listTheme = new ArrayList<Theme>();
    List<Option> setting = new ArrayList<>();
    List<Discount> discount = new ArrayList<>();
    ThemeController ThemeC = new ThemeController();
    OptionController OCC = new OptionController();

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        ImageIcon icon = new ImageIcon("src/images/circle/orderdept.png");
        Image image = icon.getImage();
        this.setIconImage(image);
        setting = OCC.getOption();
        discount = OCC.getDiscout();
        // set option
        if (setting != null || setting.size() > 0) {
            nameTheme = setting.get(0).getThemeName();
            if (nameTheme.equalsIgnoreCase("Ocean") || nameTheme.equalsIgnoreCase("Colorfull")) {
                url = "../View/images/circle/";
            }
            sellingMethod = setting.get(0).getSellingMethod();
            listTheme = ThemeC.getTheme(nameTheme);
        } else {
            listTheme = ThemeC.getTheme("dark");
        }
        // set discount
        if (discount != null || discount.size() > 0) {
            LocalDate date = LocalDate.now();
            int diss = discount.get(0).getDiscount();
            LocalDate disFromDate = discount.get(0).getFromDate();
            LocalDate disToDate = discount.get(0).getToDate();
            if (disFromDate.isAfter(date) || disToDate.isBefore(date) || diss <= 0) {
            } else {
                dis = discount.get(0).getDiscount();
                discountFromDate = discount.get(0).getFromDate();
                discountToDate = discount.get(0).getToDate();
            }
        } else {
            dis = 0;
        }

        userLabel.setText("Xin chào: " + userName);
        // GM.setLabelIcon(jLabel7, "images/order_create.png");
        Theme theme = MainJFrame.listTheme.get(0);
        taskPanel.setBackground(Color.decode(theme.getBackgroundMainPanel()));
        setColor(btnBH, bhLabel);
        resetColor(new JPanel[]{btnFile, btnNhap, btnBC}, new JLabel[]{fileLabel, nhapLabel, bcLabel});
        GM.showPanel(taskPanel, new BHPanel(this));
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int h = screenSize.height;
        int w = screenSize.width;
        int width = 0;
        int height = 0;
        if (w > 1366) {
            width = w / 10;
            height = h / 10;
        }
        setLocation(width, height);
        taskPanel.setBackground(Color.decode("#d4d2d2"));
        jPanel8.setBackground(Color.decode("#2b313b"));
        ImageIcon img = new ImageIcon("decor.png");

        Image b_img = img.getImage();
        Image temp_img = b_img.getScaledInstance(800, 35, Image.SCALE_SMOOTH);
        img = new ImageIcon(temp_img);
        JLabel back = new JLabel("", img, JLabel.CENTER);

        back.setBounds(1366 - 975, 0, 800, 35);

        jPanel8.add(back);

        taskPanel.setBackground(Color.decode(listTheme.get(0).getBackgroundTaskPanel()));
        jPanel8.setBackground(Color.decode(listTheme.get(0).getBackgroundMenuBar()));
        userLabel.setForeground(Color.decode(theme.getTxtColorTitle()));
        System.out.println("codeUser :" + codeUser + " userName: " + userName + " permisson: " + permisson);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        btnFile = new javax.swing.JPanel();
        fileLabel = new javax.swing.JLabel();
        btnBH = new javax.swing.JPanel();
        bhLabel = new javax.swing.JLabel();
        btnNhap = new javax.swing.JPanel();
        nhapLabel = new javax.swing.JLabel();
        btnBC = new javax.swing.JPanel();
        bcLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        taskPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1366, 768));

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setPreferredSize(new java.awt.Dimension(890, 35));

        btnFile.setBackground(new java.awt.Color(102, 102, 102));
        btnFile.setPreferredSize(new java.awt.Dimension(100, 35));
        btnFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFileMousePressed(evt);
            }
        });

        fileLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        fileLabel.setForeground(new java.awt.Color(255, 255, 255));
        fileLabel.setText("File");

        javax.swing.GroupLayout btnFileLayout = new javax.swing.GroupLayout(btnFile);
        btnFile.setLayout(btnFileLayout);
        btnFileLayout.setHorizontalGroup(
            btnFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileLabel)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        btnFileLayout.setVerticalGroup(
            btnFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnBH.setBackground(new java.awt.Color(102, 102, 102));
        btnBH.setPreferredSize(new java.awt.Dimension(100, 35));
        btnBH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBHMousePressed(evt);
            }
        });

        bhLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bhLabel.setForeground(new java.awt.Color(255, 255, 255));
        bhLabel.setText("Bán Hàng");

        javax.swing.GroupLayout btnBHLayout = new javax.swing.GroupLayout(btnBH);
        btnBH.setLayout(btnBHLayout);
        btnBHLayout.setHorizontalGroup(
            btnBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bhLabel)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        btnBHLayout.setVerticalGroup(
            btnBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bhLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnNhap.setBackground(new java.awt.Color(102, 102, 102));
        btnNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnNhap.setPreferredSize(new java.awt.Dimension(100, 35));
        btnNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNhapMousePressed(evt);
            }
        });

        nhapLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        nhapLabel.setForeground(new java.awt.Color(255, 255, 255));
        nhapLabel.setText("Thao tác");

        javax.swing.GroupLayout btnNhapLayout = new javax.swing.GroupLayout(btnNhap);
        btnNhap.setLayout(btnNhapLayout);
        btnNhapLayout.setHorizontalGroup(
            btnNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nhapLabel)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        btnNhapLayout.setVerticalGroup(
            btnNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nhapLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnBC.setBackground(new java.awt.Color(102, 102, 102));
        btnBC.setPreferredSize(new java.awt.Dimension(100, 35));
        btnBC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBCMousePressed(evt);
            }
        });

        bcLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bcLabel.setForeground(new java.awt.Color(255, 255, 255));
        bcLabel.setText("Báo Cáo");

        javax.swing.GroupLayout btnBCLayout = new javax.swing.GroupLayout(btnBC);
        btnBC.setLayout(btnBCLayout);
        btnBCLayout.setHorizontalGroup(
            btnBCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bcLabel)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        btnBCLayout.setVerticalGroup(
            btnBCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bcLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        userLabel.setBackground(new java.awt.Color(0, 0, 0));
        userLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(btnFile, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        taskPanel.setBackground(new java.awt.Color(179, 177, 177));
        taskPanel.setPreferredSize(new java.awt.Dimension(890, 459));
        taskPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(taskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(taskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFileMousePressed
        setColor(btnFile, fileLabel);
        resetColor(new JPanel[]{btnBH, btnNhap, btnBC}, new JLabel[]{bhLabel, nhapLabel, bcLabel});
        GM.showPanel(taskPanel, new FilePanel(this));

    }//GEN-LAST:event_btnFileMousePressed

    private void btnBHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBHMousePressed
        setColor(btnBH, bhLabel);
        resetColor(new JPanel[]{btnFile, btnNhap, btnBC}, new JLabel[]{fileLabel, nhapLabel, bcLabel});
        GM.showPanel(taskPanel, new BHPanel(this));

    }//GEN-LAST:event_btnBHMousePressed

    private void btnNhapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapMousePressed
        setColor(btnNhap, nhapLabel);
        resetColor(new JPanel[]{btnFile, btnBH, btnBC}, new JLabel[]{bhLabel, fileLabel, bcLabel});
        GM.showPanel(taskPanel, new NhapPanel(this));
    }//GEN-LAST:event_btnNhapMousePressed

    private void btnBCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBCMousePressed
        setColor(btnBC, bcLabel);
        resetColor(new JPanel[]{btnFile, btnBH, btnNhap}, new JLabel[]{bhLabel, nhapLabel, fileLabel});
        GM.showPanel(taskPanel, new BCPanel(this));
    }//GEN-LAST:event_btnBCMousePressed

    /**
     * @param args the command line arguments
     */
    public void setColor(JPanel jp, JLabel jl) {
        jp.setBackground(Color.decode(listTheme.get(0).getBackgroundTaskPanel()));

        jl.setForeground(Color.decode(listTheme.get(0).getTxtColorTitleClick()));
    }

    public void resetColor(JPanel[] pane, JLabel[] label) {
        for (int i = 0; i < pane.length; i++) {
            pane[i].setBackground(Color.decode(listTheme.get(0).getBackgroundMenuBar()));

        }
        for (int i = 0; i < label.length; i++) {
            label[i].setForeground(Color.decode(listTheme.get(0).getTxtColorTitle()));
        }

    }
//    public void resetColor(JPanel[] pane, JPanel[] indicators) {
//        for (int i = 0; i < pane.length; i++) {
//            pane[i].setBackground(Color.decode("#666666"));
//        }
//        for (int i = 0; i < indicators.length; i++) {
//            indicators[i].setOpaque(false);
//        }
//
//    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                displayJFrame();
            }
        });
    }

    public static void displayJFrame() {
        MainJFrame lts = new MainJFrame();
        lts.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        lts.setPreferredSize(new Dimension(1366, 768));
        lts.pack();
        lts.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bcLabel;
    private javax.swing.JLabel bhLabel;
    private javax.swing.JPanel btnBC;
    private javax.swing.JPanel btnBH;
    private javax.swing.JPanel btnFile;
    private javax.swing.JPanel btnNhap;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel nhapLabel;
    private javax.swing.JPanel taskPanel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
