/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.BaoCao;

import View.MainJFrame;

import DTOService.GeneralMethod;
import controller.BaoCaoController.ThuChiController;
import controller.Orders.OrderController;
import java.awt.Color;

import java.io.FileOutputStream;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.BaoCao.KhachHangBC;
import model.BaoCao.ThuChi;
import model.File.Theme;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author choco
 */
public class ThuChiPanel extends javax.swing.JPanel {

    private MainJFrame mainJFrame;
    DefaultTableModel thuChiModel;
    GeneralMethod GM = new GeneralMethod();
    ThuChiController TCC = new ThuChiController();
    OrderController OC = new OrderController();
    List<ThuChi> listThuchi;
    Theme theme = MainJFrame.listTheme.get(0);

    /**
     * Creates new form ThuCHiOanel
     */
    public ThuChiPanel(MainJFrame mainJFrame) {
        initComponents();
        this.mainJFrame = mainJFrame;
        ///khai set mau --------------
        setColor();
        //set icon
        GM.setLabelIcon(iconPrint, MainJFrame.url + "chiTien.png");
        GM.setLabelIcon(iconExcel, MainJFrame.url + "excel.png");
        thuChiModel = (DefaultTableModel) thuChiTable.getModel();
        // set max Size của từng cột
        thuChiTable.getColumnModel().getColumn(0).setMaxWidth(50);
        //thuChiTable.getColumnModel().getColumn(1).setMaxWidth(250);
        System.out.println(MainJFrame.userName);
        DefaultTableCellRenderer renderRight = new DefaultTableCellRenderer();

        { // initializer block
            renderRight.setHorizontalAlignment(SwingConstants.RIGHT);
        }
        thuChiTable.setDefaultRenderer(thuChiTable.getColumnClass(0), renderRight);

        formatBoxLoaiKhach(monthYearBox);
        formatBoxLoaiKhach(yearBox);
        dateText.setText(GM.dateToStr(LocalDate.now()));
        int x = this.mainJFrame.getLocationOnScreen().x + 400;
        int y = this.mainJFrame.getLocationOnScreen().y + 100;
        ChiTienDialog.setLocation(x, y);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChiTienDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        chiChoText = new javax.swing.JTextField();
        soTienChiText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        dienGiaiText = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCancle = new javax.swing.JButton();
        btnChitien = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        thuChiTable = new javax.swing.JTable();
        fitterPanel = new javax.swing.JPanel();
        btnDay = new javax.swing.JButton();
        dateText = new javax.swing.JFormattedTextField();
        monthBox = new javax.swing.JComboBox<>();
        btnMonth = new javax.swing.JButton();
        btnYear = new javax.swing.JButton();
        yearBox = new javax.swing.JComboBox<>();
        monthYearBox = new javax.swing.JComboBox<>();
        actionPanel = new javax.swing.JPanel();
        btnChi = new javax.swing.JPanel();
        iconPrint = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnRemoveSelected1 = new javax.swing.JPanel();
        iconExcel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tonDauText = new javax.swing.JLabel();
        tonCuoiText = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tongChiText = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tongThuText = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inforText = new javax.swing.JLabel();

        ChiTienDialog.setBackground(new java.awt.Color(102, 102, 102));
        ChiTienDialog.setUndecorated(true);
        ChiTienDialog.setSize(new java.awt.Dimension(400, 300));

        chiChoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiChoTextActionPerformed(evt);
            }
        });

        dienGiaiText.setColumns(20);
        dienGiaiText.setRows(5);
        jScrollPane2.setViewportView(dienGiaiText);

        jLabel4.setText("Số tiền:");

        jLabel8.setText("Chi cho:");

        jLabel6.setText("DIễn giải:");

        btnCancle.setText("Cancle");
        btnCancle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancleMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancleMouseReleased(evt);
            }
        });

        btnChitien.setText("OK");
        btnChitien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnChitienMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancle, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnChitien, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chiChoText)
                            .addComponent(soTienChiText)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(soTienChiText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chiChoText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel6)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancle)
                    .addComponent(btnChitien))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout ChiTienDialogLayout = new javax.swing.GroupLayout(ChiTienDialog.getContentPane());
        ChiTienDialog.getContentPane().setLayout(ChiTienDialogLayout);
        ChiTienDialogLayout.setHorizontalGroup(
            ChiTienDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ChiTienDialogLayout.setVerticalGroup(
            ChiTienDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        thuChiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Ngày/Month", "Thu", "Chi", "Tồn cuối", "DIễn giải"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(thuChiTable);

        fitterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hiển Thị", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Dialog", 0, 13))); // NOI18N

        btnDay.setText("Trong Ngày");
        btnDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDayMousePressed(evt);
            }
        });

        try {
            dateText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dateText.setToolTipText("Định dạng ngày: 25/03/2020");

        monthBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        btnMonth.setText("Trong Tháng");
        btnMonth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMonthMousePressed(evt);
            }
        });

        btnYear.setText("Trong Năm");
        btnYear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnYearMousePressed(evt);
            }
        });

        javax.swing.GroupLayout fitterPanelLayout = new javax.swing.GroupLayout(fitterPanel);
        fitterPanel.setLayout(fitterPanelLayout);
        fitterPanelLayout.setHorizontalGroup(
            fitterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fitterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fitterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateText, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(yearBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fitterPanelLayout.createSequentialGroup()
                        .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthYearBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(5, 5, 5)
                .addGroup(fitterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fitterPanelLayout.createSequentialGroup()
                        .addComponent(btnMonth)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        fitterPanelLayout.setVerticalGroup(
            fitterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fitterPanelLayout.createSequentialGroup()
                .addGroup(fitterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDay))
                .addGap(18, 18, 18)
                .addGroup(fitterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMonth)
                    .addComponent(monthYearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fitterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnYear)))
        );

        actionPanel.setBackground(new java.awt.Color(110, 110, 110));
        actionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Action", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        actionPanel.setForeground(new java.awt.Color(255, 255, 255));

        btnChi.setBackground(new java.awt.Color(179, 177, 177));
        btnChi.setPreferredSize(new java.awt.Dimension(101, 99));
        btnChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnChiMousePressed(evt);
            }
        });

        iconPrint.setAlignmentX(0.5F);
        iconPrint.setPreferredSize(new java.awt.Dimension(60, 60));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Chi tiền");

        javax.swing.GroupLayout btnChiLayout = new javax.swing.GroupLayout(btnChi);
        btnChi.setLayout(btnChiLayout);
        btnChiLayout.setHorizontalGroup(
            btnChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnChiLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(iconPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        btnChiLayout.setVerticalGroup(
            btnChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnChiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconPrint, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addGap(0, 0, 0))
        );

        btnRemoveSelected1.setBackground(new java.awt.Color(179, 177, 177));
        btnRemoveSelected1.setPreferredSize(new java.awt.Dimension(101, 99));
        btnRemoveSelected1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRemoveSelected1MousePressed(evt);
            }
        });

        iconExcel.setAlignmentX(0.5F);
        iconExcel.setPreferredSize(new java.awt.Dimension(60, 60));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Xuất Excel");

        javax.swing.GroupLayout btnRemoveSelected1Layout = new javax.swing.GroupLayout(btnRemoveSelected1);
        btnRemoveSelected1.setLayout(btnRemoveSelected1Layout);
        btnRemoveSelected1Layout.setHorizontalGroup(
            btnRemoveSelected1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRemoveSelected1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(iconExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        btnRemoveSelected1Layout.setVerticalGroup(
            btnRemoveSelected1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRemoveSelected1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconExcel, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(jLabel10)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
        actionPanel.setLayout(actionPanelLayout);
        actionPanelLayout.setHorizontalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnRemoveSelected1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        actionPanelLayout.setVerticalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemoveSelected1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Tồn đầu kỳ:");

        jLabel2.setText("Tồn cuối kỳ :");

        tonDauText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tonDauText.setText("0");

        tonCuoiText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tonCuoiText.setText("0");

        jLabel5.setText("Tổng chi trong kỳ");

        tongChiText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tongChiText.setText("0");

        jLabel9.setText("Tổng thu trong kỳ:");

        tongThuText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tongThuText.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tongThuText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tongChiText, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tonDauText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tonCuoiText, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tongThuText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tongChiText)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tonDauText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tonCuoiText)
                            .addComponent(jLabel2))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel3.setText("Bạn đang xem Thu Chi của :");

        inforText.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        inforText.setForeground(new java.awt.Color(204, 0, 0));
        inforText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(fitterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jLabel3))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(inforText, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fitterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(inforText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents
private void setColor() {
        Theme theme = MainJFrame.listTheme.get(0);
        thuChiTable.getTableHeader().setOpaque(false);
        thuChiTable.getTableHeader().setBackground(Color.decode(theme.getBackgroundTittleTable()));
        btnDay.setBackground(Color.decode(theme.getBackgroundButton()));
        btnMonth.setBackground(Color.decode(theme.getBackgroundButton()));
        btnYear.setBackground(Color.decode(theme.getBackgroundButton()));
        btnChitien.setBackground(Color.decode(theme.getBackgroundButton()));
        btnCancle.setBackground(Color.decode(theme.getBackgroundButton()));
        monthBox.setBackground(Color.decode(theme.getBackgroundTextField()));
        monthYearBox.setBackground(Color.decode(theme.getBackgroundTextField()));
        yearBox.setBackground(Color.decode(theme.getBackgroundTextField()));
        actionPanel.setBackground(Color.decode(theme.getBackgroundMainPanel()));
        fitterPanel.setBackground(Color.decode(theme.getBackgroundMainPanel()));
        jPanel1.setBackground(Color.decode(theme.getBackgroundMainPanel()));
        this.setBackground(Color.decode(theme.getBackgroundMainPanel()));

        ChiTienDialog.setBackground(Color.decode(theme.getBackgroundMainPanel()));

        btnRemoveSelected1.setBackground(Color.decode(theme.getBackgroundMainPanel()));
        btnChi.setBackground(Color.decode(theme.getBackgroundMainPanel()));
        jLabel3.setForeground(Color.decode(theme.getTxtColorTitle()));
        jLabel10.setForeground(Color.decode(theme.getTxtColorTitle()));
        jLabel7.setForeground(Color.decode(theme.getTxtColorTitle()));
        jLabel4.setForeground(Color.decode(theme.getTxtColorTitle()));
        jLabel6.setForeground(Color.decode(theme.getTxtColorTitle()));
        jLabel8.setForeground(Color.decode(theme.getTxtColorTitle()));
        inforText.setForeground(Color.decode(theme.getTxtColorTitle()));
    }
    private void btnChiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChiMousePressed

        ChiTienDialog.setVisible(true);

        this.mainJFrame.setEnabled(false);

    }//GEN-LAST:event_btnChiMousePressed

    private void btnDayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDayMousePressed
        try {
            if (listThuchi != null) {
                listThuchi.removeAll(listThuchi);
            }
            LocalDate date = GM.strToDate(dateText.getText(), "dd/MM/yyyy");
            listThuchi = TCC.getThuChiByDate(date);
            showTCTable(listThuchi);
            inforText.setText("Ngày: " + GM.dateToStr(date));
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Vui lòng nhập vào ngày");

        }
    }//GEN-LAST:event_btnDayMousePressed

    private void btnMonthMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthMousePressed
        try {
            if (listThuchi != null) {
                listThuchi.removeAll(listThuchi);
            }
            int month = Integer.parseInt(monthBox.getSelectedItem().toString());
            int year = Integer.parseInt(monthYearBox.getSelectedItem().toString());
            listThuchi = TCC.getThuChiByMonth(month, year);
            showTCTable(listThuchi);
            inforText.setText("Tháng: " + month + "/" + year);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Vui lòng lựa chọn tháng + năm");

        }
    }//GEN-LAST:event_btnMonthMousePressed

    private void btnYearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYearMousePressed
        try {
            if (listThuchi != null) {
                listThuchi.removeAll(listThuchi);
            }

            int year = Integer.parseInt(yearBox.getSelectedItem().toString());
            listThuchi = TCC.getThuChiByYear(year);
            showTCTable(listThuchi);
            inforText.setText("Năm : " + year);
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Vui lòng chọn năm");

        }
    }//GEN-LAST:event_btnYearMousePressed

    private void btnRemoveSelected1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveSelected1MousePressed
        exportExcel(listThuchi);
    }//GEN-LAST:event_btnRemoveSelected1MousePressed
// chi tien
    private void btnChitienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChitienMousePressed
        // chi tien

        String des = dienGiaiText.getText();
        String chiCho = chiChoText.getText();
        String dienGiai = MainJFrame.userName + " chi : " + des + " cho  : " + chiCho;
        Double tienChi = 0.0;
        try {
            tienChi = Double.parseDouble(soTienChiText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kiểm tra lại số tiền!");
        }
        if (tienChi > 0) {
            if (tienChi <= TCC.getTonCuoi()) {
                if (OC.insertChi(MainJFrame.codeUser, tienChi, dienGiai)) {
                    JOptionPane.showMessageDialog(null, "Chi thành công");
                    ChiTienDialog.setVisible(false);
                    this.mainJFrame.setEnabled(true);
                    this.mainJFrame.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Chi tiền thất bại");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Số tiền chi lớn hơn quỹ!");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Kiểm tra lại số tiền!");
        }
    }//GEN-LAST:event_btnChitienMousePressed

    private void btnCancleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancleMousePressed
        ChiTienDialog.setVisible(false);
        this.mainJFrame.setEnabled(true);
        this.mainJFrame.setVisible(true);
    }//GEN-LAST:event_btnCancleMousePressed

    private void btnCancleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancleMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancleMouseReleased

    private void chiChoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiChoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chiChoTextActionPerformed

    public void showTCTable(List<ThuChi> list) {
        thuChiModel.setRowCount(0);
        if (list.size() > 0) {
            int no = 1;
            Double tonDau = list.get(0).getTonQuy() - list.get(0).getThu() + list.get(0).getChi();
            Double tonCuoi = list.get(list.size() - 1).getTonQuy();
            Double tongThu = 0.0;
            Double tongChi = 0.0;
            for (ThuChi lts : list) {
                tongThu += lts.getThu();
                tongChi += lts.getChi();
            }
            tonDauText.setText(GM.doubleToDecimal(tonDau));
            tonCuoiText.setText(GM.doubleToDecimal(tonCuoi));
            tongThuText.setText(GM.doubleToDecimal(tongThu));
            tongChiText.setText(GM.doubleToDecimal(tongChi));
            for (ThuChi lts : list) {
                thuChiModel.addRow(new Object[]{
                    no++, lts.getDate(), GM.doubleToDecimal(lts.getThu()), GM.doubleToDecimal(lts.getChi()), GM.doubleToDecimal(lts.getTonQuy()), lts.getDescription()
                });
            }
        } else {

            JOptionPane.showMessageDialog(null, "Không có dữ liệu trong thời gian này!");
        }

    }

    public void exportExcel(List<ThuChi> list) {
        JFileChooser excelFileChooser = new JFileChooser("C:\\Users\\"); //  duong dan
        excelFileChooser.setDialogTitle("Save As");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlsx", "xlsm");
        excelFileChooser.setFileFilter(fnef);
        int excelChooser = excelFileChooser.showSaveDialog(null);

        if (excelChooser == JFileChooser.APPROVE_OPTION) {
            try {
                XSSFWorkbook workbook = new XSSFWorkbook();
                XSSFSheet spreadsheet = workbook.createSheet("Khach Hang");

                XSSFRow row = null;
                Cell cell = null;

                row = spreadsheet.createRow((short) 2);
                row.setHeight((short) 500);
                cell = row.createCell(0, CellType.STRING);
                cell.setCellValue("DANH SACH THU CHI");

                row = spreadsheet.createRow((short) 3);
                row.setHeight((short) 500);
                cell = row.createCell(0, CellType.STRING);
                cell.setCellValue("STT");
                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue("Ngay/Month");
                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue("Thu");
                cell = row.createCell(3, CellType.STRING);
                cell.setCellValue("Chi");
                cell = row.createCell(4, CellType.STRING);
                cell.setCellValue("Ton cuoi");
                cell = row.createCell(5, CellType.NUMERIC);
                cell.setCellValue("Dien giai");

                for (int i = 0; i < list.size(); i++) {
                    ThuChi tc = list.get(i);
                    row = spreadsheet.createRow((short) 4 + i);
                    row.setHeight((short) 400);
                    row.createCell(0).setCellValue(i + 1);
                    row.createCell(1).setCellValue(tc.getDate());
                    row.createCell(2).setCellValue(tc.getThu());
                    row.createCell(3).setCellValue(tc.getChi());
                    row.createCell(4).setCellValue(tc.getTonQuy());
                    row.createCell(5).setCellValue(tc.getDescription());
                }

                FileOutputStream out = new FileOutputStream(excelFileChooser.getSelectedFile() + ".xlsx");
                workbook.write(out);
                JOptionPane.showMessageDialog(null, "Xuất file thành công");
                out.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }

    public void formatBoxLoaiKhach(JComboBox box) {
        int year = LocalDate.now().getYear();
        box.removeAllItems();
        box.addItem("");
        box.addItem(year);
        box.addItem(year - 1);
        box.addItem(year - 2);
        box.addItem(year - 3);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ChiTienDialog;
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton btnCancle;
    private javax.swing.JPanel btnChi;
    private javax.swing.JButton btnChitien;
    private javax.swing.JButton btnDay;
    private javax.swing.JButton btnMonth;
    private javax.swing.JPanel btnRemoveSelected1;
    private javax.swing.JButton btnYear;
    private javax.swing.JTextField chiChoText;
    private javax.swing.JFormattedTextField dateText;
    private javax.swing.JTextArea dienGiaiText;
    private javax.swing.JPanel fitterPanel;
    private javax.swing.JLabel iconExcel;
    private javax.swing.JLabel iconPrint;
    private javax.swing.JLabel inforText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> monthBox;
    private javax.swing.JComboBox<String> monthYearBox;
    private javax.swing.JTextField soTienChiText;
    private javax.swing.JTable thuChiTable;
    private javax.swing.JLabel tonCuoiText;
    private javax.swing.JLabel tonDauText;
    private javax.swing.JLabel tongChiText;
    private javax.swing.JLabel tongThuText;
    private javax.swing.JComboBox<String> yearBox;
    // End of variables declaration//GEN-END:variables
}
